package Interfaz;

import Clases.Carrito;
import Clases.Cliente;
import Clases.Libro;
import Clases.Vendedor;
import Clases.Venta;
import milibreria.*;

import java.util.ArrayList;
import static proyectolibreria.ProyectoLibreria.usuarios;

public class ventanaLibreria extends javax.swing.JFrame {

    /**
     * Creates new form ventanaLibreria
     */
    ArrayList<Cliente> listaClientes = new ArrayList<>();
    ArrayList<Libro> listaLibros = new ArrayList<>();
    ArrayList<Carrito> listaCarrito = new ArrayList<>();
    ArrayList<Vendedor> listaVendedores = new ArrayList<>();
    ArrayList<Venta> ventas = new ArrayList<>();
    

    public ventanaLibreria(ArrayList<Cliente> listaClientes, ArrayList<Libro> listaLibros, ArrayList<Carrito> listaCarrito, ArrayList<Vendedor> listaVendedores, ArrayList<Venta> ventas) {
      
        this.listaClientes = listaClientes;
        this.listaLibros = listaLibros;
        this.listaVendedores=listaVendedores;
        this.listaCarrito= listaCarrito;
        this.ventas=ventas;
        

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMiCuenta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMiCuenta.setBackground(new java.awt.Color(0, 0, 0));
        botonMiCuenta.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        botonMiCuenta.setForeground(new java.awt.Color(0, 204, 204));
        botonMiCuenta.setText("Log In");
        botonMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMiCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(botonMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 60, 322, 67));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("More");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 96, 29));

        jLabel3.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("a");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 110, 30));

        jLabel4.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("READ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 140, 50));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("than");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.jpg"))); // NOI18N
        jLabel1.setText("A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMiCuentaActionPerformed

        usuarios.AñadirUsuario("manager", "123", 0);
        usuarios.AñadirUsuario("cliente", "123", 1);

        for (int i = 0; i < listaClientes.size(); i++) {
            usuarios.AñadirUsuario(listaClientes.get(i).getUsuario(),listaClientes.get(i).getContraseña(),1);
        }
  
        
        if (usuarios.contraseñaIntentos()) {
            if (usuarios.nivelUsuActivo() == 0 ) {
                new ventanaManager(listaClientes, listaLibros,ventas).setVisible(true);
               
                ventanaManager.usu1.setText(usuarios.nombreUsuActivo());
                ventanaManager.nivel1.setText(Integer.toString(usuarios.nivelUsuActivo()));

            } else if (usuarios.nivelUsuActivo() == 1) {
                new ventanaCliente(listaLibros,listaClientes,ventas,listaVendedores).setVisible(true);
               
                ventanaCliente.cliente1.setText(usuarios.nombreUsuActivo());
              

            }

        }
    }//GEN-LAST:event_botonMiCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMiCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
