/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;


import Clases.GeneroTypes;
import Clases.Libro;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import milibreria.FuncionesGraficas;
import static proyectolibreria.ProyectoLibreria.escribirFicheroLibros;

/**
 *
 * @author Salva
 */
public class ventanaAñadirLibro extends javax.swing.JFrame {

    private ArrayList<Libro> listaLibros = new ArrayList<Libro>();
    String rutaFichero = new String();
    String foto = new String();
    public ventanaAñadirLibro(ArrayList<Libro> listaLibros) {
      
        this.listaLibros = listaLibros;
        initComponents();
        combo = new JComboBox(GeneroTypes.values());     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoPrecio = new javax.swing.JTextField();
        confirmarAlta = new javax.swing.JButton();
        cancelarAlta = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        campoFoto = new javax.swing.JLabel();
        añadirFoto = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoIsbn = new javax.swing.JTextField();
        campoAutor = new javax.swing.JTextField();
        campoGenero = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(campoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 196, 44, -1));

        confirmarAlta.setText("Confirmar");
        confirmarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarAltaActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        cancelarAlta.setText("Cancelar");
        cancelarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAltaActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        mensaje.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 441, 26));

        campoFoto.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(campoFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, 130));

        añadirFoto.setText("Añadir Foto");
        añadirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirFotoActionPerformed(evt);
            }
        });
        jPanel1.add(añadirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 115, -1, -1));

        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 25, 42, -1));

        jLabel2.setText("Autor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 64, -1, -1));

        jLabel3.setText("Género");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, -1, -1));

        jLabel4.setText("Título");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 154, -1, -1));

        jLabel5.setText("Precio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(campoIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 26));
        jPanel1.add(campoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 126, -1));
        jPanel1.add(campoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 108, 136, -1));
        jPanel1.add(campoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 150, 146, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioActionPerformed

    }//GEN-LAST:event_campoPrecioActionPerformed

    private void cancelarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAltaActionPerformed

        dispose();
    }//GEN-LAST:event_cancelarAltaActionPerformed


    private void confirmarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarAltaActionPerformed
        
        if ((campoIsbn.getText().isEmpty()) || (campoIsbn.getText().isBlank())) {
            mensaje.setText("Debe introducir el ISBN");
        } else if ((campoAutor.getText().isEmpty()) || (campoAutor.getText().isBlank())) {
            mensaje.setText("Debe introducir en nombre el autor");
        } else if ((campoGenero.getText().isEmpty()) || (campoGenero.getText().isBlank())) {
            mensaje.setText("Debe introducir el género del libro");
        } else if ((campoTitulo.getText().isEmpty()) || (campoTitulo.getText().isBlank())) {
            mensaje.setText("Debe introducir el título del libro");
        } else if ((campoPrecio.getText().isEmpty() || (campoPrecio.getText().isBlank()))) {
            mensaje.setText("Debes introducir un precio");
        } else if (rutaFichero.isEmpty()) {
            mensaje.setText("Debes adjuntar una foto del libro");
        } else {
            Libro nuevoLibro = new Libro(Integer.parseInt(campoIsbn.getText()), campoAutor.getText(), GeneroTypes.valueOf(campoGenero.getText()), campoTitulo.getText(),
                    Double.parseDouble(campoPrecio.getText()), rutaFichero);
            listaLibros.add(nuevoLibro);
              escribirFicheroLibros(listaLibros);
            mensaje.setText("Libro añadido correctamente");
            campoIsbn.setText(null);
            campoAutor.setText(null);
            campoGenero.setText(null);
            campoTitulo.setText(null);
            campoPrecio.setText(null);
            campoFoto.setText(null);
            rutaFichero = "";
        }

    }//GEN-LAST:event_confirmarAltaActionPerformed

    private void añadirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirFotoActionPerformed
     
         ventanaCargarFoto nuevaFoto = new ventanaCargarFoto();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG,JPEG,PNG y BMP", "jpg", "jpeg", "png", "bmp");

        nuevaFoto.getJFileChooser().setFileFilter(filtro);

        int resultado = nuevaFoto.getJFileChooser().showOpenDialog(null);
        rutaFichero=nuevaFoto.getJFileChooser().getSelectedFile().toString();

        if (resultado != JFileChooser.CANCEL_OPTION) {
            ImageIcon icon = new ImageIcon(nuevaFoto.getJFileChooser().getSelectedFile().toString());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(campoFoto.getWidth(), campoFoto.getHeight(), Image.SCALE_DEFAULT));
            campoFoto.setIcon(icono);
            }
    }//GEN-LAST:event_añadirFotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirFoto;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JLabel campoFoto;
    private javax.swing.JTextField campoGenero;
    private javax.swing.JTextField campoIsbn;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JButton cancelarAlta;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton confirmarAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
