/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Carrito;
import Clases.Cliente;
import Clases.Libro;
import Clases.Vendedor;
import Clases.Venta;
import java.util.ArrayList;

/**
 *
 * @author Salva
 */
public class ventanaCliente extends javax.swing.JFrame {

    private ArrayList<Libro> listaLibros = new ArrayList<>();
    private ArrayList<Cliente> listaClientes = new ArrayList<>();
    private ArrayList<Vendedor> listaVendedores = new ArrayList<>();
    private Carrito carrito1 = new Carrito();
   private ArrayList<Carrito> listaCarrito = new ArrayList<>();
    private ArrayList<Venta>listaVentas;

    public ventanaCliente(ArrayList<Libro> listaLibros, ArrayList<Cliente>listaClientes,ArrayList<Venta>listaVentas, ArrayList<Vendedor> listaVendedores ) {
        this.listaVentas=listaVentas;
        this.listaClientes=listaClientes;
        this.listaLibros = listaLibros;
        this.carrito1 = carrito1;
        this.listaCarrito=listaCarrito;
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cliente1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonCarrito = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonLista = new javax.swing.JButton();
        botonSalirApp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cielo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cliente1.setBackground(new java.awt.Color(255, 255, 255));
        cliente1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cliente1.setForeground(new java.awt.Color(0, 0, 0));
        cliente1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 140, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 170, 40));

        botonCarrito.setBackground(new java.awt.Color(0, 0, 0));
        botonCarrito.setForeground(new java.awt.Color(255, 255, 255));
        botonCarrito.setText("Carrito");
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salva\\Desktop\\PROYECTO LIBRERIA\\Fotos\\books_library_study_icon_150963 (1).png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 230, 200));

        botonLista.setBackground(new java.awt.Color(0, 0, 0));
        botonLista.setForeground(new java.awt.Color(255, 255, 255));
        botonLista.setText("Comprar");
        botonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaActionPerformed(evt);
            }
        });
        getContentPane().add(botonLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 180, 50));

        botonSalirApp.setBackground(new java.awt.Color(0, 0, 0));
        botonSalirApp.setForeground(new java.awt.Color(255, 255, 255));
        botonSalirApp.setText("Salir de la APP");
        botonSalirApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirAppActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalirApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 159, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("More Than A Read");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 430, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salva\\Desktop\\AZULEJO-75-X-15-LISO-BRILLO-COLOR-AMARILLO-CLARO.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaActionPerformed
        new ventanaClienteLibros(listaLibros, carrito1).setVisible(true);
    }//GEN-LAST:event_botonListaActionPerformed

    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        new ventanaCarrito(this.carrito1,this.listaVentas).setVisible(true);
    }//GEN-LAST:event_botonCarritoActionPerformed

    private void botonSalirAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirAppActionPerformed

        new ventanaLibreria(listaClientes, listaLibros, listaCarrito, listaVendedores, listaVentas).setVisible(true);
    }//GEN-LAST:event_botonSalirAppActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarrito;
    private javax.swing.JButton botonLista;
    private javax.swing.JButton botonSalirApp;
    public static javax.swing.JLabel cliente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
