/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.GeneroTypes;
import Clases.Libro;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class ventanaListaLibros extends javax.swing.JFrame {

    private ArrayList<Libro> listaLibros = new ArrayList<>();
    int contador = 0;
    private boolean click=true;
    
    public ventanaListaLibros(ArrayList <Libro> listaLibros) {
        this.listaLibros=listaLibros;
        initComponents();
        campoNumero.setText(String.valueOf(listaLibros.size()));
        cargarLibros();
    }

    public void cargarLibros() {
        String[] cabecera = {"Isbn ", "Autor ", "Género ", "Título", "Precio"};
        String[][] datosClientes = new String[listaLibros.size()][5];
        for (int i = 0; i < listaLibros.size(); i++) {
            datosClientes[i][0] = String.valueOf(listaLibros.get(i).getIsbn());
            datosClientes[i][1] = listaLibros.get(i).getAutor();
            datosClientes[i][2] = String.valueOf(listaLibros.get(i).getGenero());
            datosClientes[i][3] = listaLibros.get(i).getTitulo();
            
            datosClientes[i][4] =  String.valueOf(listaLibros.get(i).getPrecio());
        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(datosClientes, cabecera));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoNumero = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ordenar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 163));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nº de Libros:");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        campoNumero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        campoNumero.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 43, 42));

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, -1));

        ordenar.setText("Ordenar por título");
        ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarActionPerformed(evt);
            }
        });
        getContentPane().add(ordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salva\\Desktop\\fondo-hormigon-color-azul-turquesa-claro-color-suave_190474-297.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
      
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     public void ordenar(ArrayList<Libro> listaLibros,int campo,int orden)
    {
      //TODO
      int isbn;
     
      String titulo=new String();
      String autor=new String();
      
      
      if (orden==0) 
      {
       
         for(int i=0;i<listaLibros.size();i++)
          for(int j=listaLibros.size()-1;j>i;j--)
           if (listaLibros.get(j).getTitulo().compareTo(listaLibros.get(i).getTitulo())>0)
           {
            isbn=listaLibros.get(i).getIsbn();
            listaLibros.get(i).setIsbn(listaLibros.get(j).getIsbn());
            listaLibros.get(j).setIsbn(isbn);
            
            titulo=listaLibros.get(i).getTitulo();
            listaLibros.get(i).setTitulo(listaLibros.get(j).getTitulo());
            listaLibros.get(j).setTitulo(titulo);
            
            autor=listaLibros.get(i).getAutor();
            listaLibros.get(i).setAutor(listaLibros.get(j).getAutor());
            listaLibros.get(j).setAutor(autor);
    
           }
      }
      else 
      {
         for(int i=0;i<listaLibros.size();i++)
          for(int j=listaLibros.size()-1;j>i;j--)
           if (listaLibros.get(j).getTitulo().compareTo(listaLibros.get(i).getTitulo())<0)
           {
            isbn=listaLibros.get(i).getIsbn();
            listaLibros.get(i).setIsbn(listaLibros.get(j).getIsbn());
            listaLibros.get(j).setIsbn(isbn);
            
            titulo=listaLibros.get(i).getTitulo();
            listaLibros.get(i).setTitulo(listaLibros.get(j).getTitulo());
            listaLibros.get(j).setTitulo(titulo);
           }
      }      
    }
    

    private void ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarActionPerformed
         if (click) 
      {
        ordenar(listaLibros,3,0); //1 - Codigo, 2- Descripcion y 3 - Ruta fichero
                               //0 - Ascendente 1- Descendente  
        click=false;
      }
      else 
      {
        ordenar(listaLibros,3,1);
        click=true;
      }
      cargarLibros();
                                               
    }//GEN-LAST:event_ordenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoNumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ordenar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
