/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Carrito;
import Clases.Libro;

import Clases.Venta;
import java.util.ArrayList;
import milibreria.FuncionesGraficas;
import proyectolibreria.ProyectoLibreria;

/**
 *
 * @author Salva
 */
public class ventanaCarrito extends javax.swing.JFrame {

    private Carrito carrito;
    private ArrayList<Venta> ventas = new ArrayList<Venta>();

    public ventanaCarrito(Carrito carrito,ArrayList<Venta> ventas) {
        this.ventas = ventas;
        this.carrito = carrito;
        initComponents();
        cargarCarrito();
    }

    public void cargarCarrito() {
        String[] cabecera = {"Titulo ", "Precio "};
        String[][] datosLineaVenta = new String[carrito.getVentasCarrito().size()][2];
        for (int i = 0; i < carrito.getVentasCarrito().size(); i++) {
            datosLineaVenta[i][0] = carrito.getVentasCarrito().get(i).getLibroLineaVenta().getTitulo();
            datosLineaVenta[i][1] = String.valueOf(carrito.getVentasCarrito().get(i).getLibroLineaVenta().getPrecio());
        }
        jTable.setModel(new javax.swing.table.DefaultTableModel(datosLineaVenta, cabecera));

        txtPrecioFinal.setText(String.valueOf(this.carrito.calcularPrecioFinalCarrito()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonComprar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioFinal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonComprar.setBackground(new java.awt.Color(0, 0, 0));
        botonComprar.setForeground(new java.awt.Color(255, 255, 255));
        botonComprar.setText("Comprar");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });
        getContentPane().add(botonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 60, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Carrito");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, -1));

        jLabel2.setText("Precio total a pagar :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));
        getContentPane().add(txtPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 60, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 330, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salva\\Desktop\\AZULEJO-75-X-15-LISO-BRILLO-COLOR-AMARILLO-CLARO.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        
        for (int i = 0; i < carrito.getVentasCarrito().size(); i++) {
            Venta lv = carrito.getVentasCarrito().get(i);
            ventas.add(lv);
            ProyectoLibreria.escribirFicheroVentas(ventas);
        }
        FuncionesGraficas.mostrarDatos("Enhorabuena", "Compra realizada con éxito");
        dispose();
    }//GEN-LAST:event_botonComprarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked

    }//GEN-LAST:event_jTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtPrecioFinal;
    // End of variables declaration//GEN-END:variables
}
