/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Carrito;
import Clases.Libro;
import Clases.Venta;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Salva
 */
public class ventanaClienteLibros extends javax.swing.JFrame {

    private ArrayList<Libro> listaLibros;
    private Carrito carrito;
    
    public ventanaClienteLibros(ArrayList<Libro> listaLibros, Carrito carrito) {
        this.carrito = carrito;
        this.listaLibros = listaLibros;
        initComponents();
        cargarLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoAutor = new javax.swing.JLabel();
        campoGenero = new javax.swing.JLabel();
        campoIsbn = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JLabel();
        campoFoto = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        añadirCarrito = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 150));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Isbn :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 59, 24));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Autor :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 59, 24));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Título :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 59, 24));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Género : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 59, 24));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Portada :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 59, 24));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Precio : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 59, 24));

        campoAutor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoAutor.setForeground(new java.awt.Color(0, 0, 0));
        campoAutor.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 110, 24));

        campoGenero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoGenero.setForeground(new java.awt.Color(0, 0, 0));
        campoGenero.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 109, 24));

        campoIsbn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoIsbn.setForeground(new java.awt.Color(0, 0, 0));
        campoIsbn.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 54, 24));

        campoPrecio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoPrecio.setForeground(new java.awt.Color(0, 0, 0));
        campoPrecio.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 60, 24));

        campoFoto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoFoto.setForeground(new java.awt.Color(0, 0, 0));
        campoFoto.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 130, 110));

        campoTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        campoTitulo.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(campoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 242, 24));

        botonAtras.setBackground(new java.awt.Color(0, 0, 0));
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("Salir");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 390, 70, -1));

        añadirCarrito.setBackground(new java.awt.Color(0, 0, 0));
        añadirCarrito.setForeground(new java.awt.Color(255, 255, 255));
        añadirCarrito.setText("Añadir al carrito");
        añadirCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(añadirCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 390, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Salva\\Desktop\\AZULEJO-75-X-15-LISO-BRILLO-COLOR-AMARILLO-CLARO.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 610, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        campoIsbn.setText(String.valueOf(listaLibros.get(tabla.getSelectedRow()).getIsbn()));
        campoAutor.setText(listaLibros.get(tabla.getSelectedRow()).getAutor());
        campoGenero.setText(String.valueOf(listaLibros.get(tabla.getSelectedRow()).getGenero()));
        campoTitulo.setText(listaLibros.get(tabla.getSelectedRow()).getTitulo());
        campoPrecio.setText(String.valueOf(listaLibros.get(tabla.getSelectedRow()).getPrecio()));

        ImageIcon icon = new ImageIcon(listaLibros.get(tabla.getSelectedRow()).getRutaFoto());
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(campoFoto.getWidth(), campoFoto.getHeight(), Image.SCALE_DEFAULT));
        campoFoto.setIcon(icono);
    }//GEN-LAST:event_tablaMouseClicked

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        campoIsbn.setText(String.valueOf(listaLibros.get(tabla.getSelectedRow()).getIsbn()));
        campoAutor.setText(listaLibros.get(tabla.getSelectedRow()).getAutor());
        campoGenero.setText(String.valueOf(listaLibros.get(tabla.getSelectedRow()).getGenero()));
        campoTitulo.setText(listaLibros.get(tabla.getSelectedRow()).getTitulo());
        campoPrecio.setText(String.valueOf(listaLibros.get(tabla.getSelectedRow()).getPrecio()));

        ImageIcon icon = new ImageIcon(listaLibros.get(tabla.getSelectedRow()).getRutaFoto());
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(campoFoto.getWidth(), campoFoto.getHeight(), Image.SCALE_DEFAULT));
        campoFoto.setIcon(icono);
    }//GEN-LAST:event_tablaKeyPressed

    private void añadirCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirCarritoActionPerformed
        
        Venta lv = new Venta(listaLibros.get(tabla.getSelectedRow()),1);
        //lv.setFecha(new Date());
        this.carrito.agregarLineaVenta(lv);
    }//GEN-LAST:event_añadirCarritoActionPerformed

    public void cargarLibros() {
        String[] cabecera = {"Isbn ", "Autor ", "Género ", "Título", "Precio"};
        String[][] datosLibros = new String[listaLibros.size()][5];
        for (int i = 0; i < listaLibros.size(); i++) {
            datosLibros[i][0] = String.valueOf(listaLibros.get(i).getIsbn());
            datosLibros[i][1] = listaLibros.get(i).getAutor();
            datosLibros[i][2] = String.valueOf(listaLibros.get(i).getGenero());
            datosLibros[i][3] = listaLibros.get(i).getTitulo();
            datosLibros[i][4] = String.valueOf(listaLibros.get(i).getPrecio());
        }

        tabla.setModel(new javax.swing.table.DefaultTableModel(datosLibros, cabecera));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirCarrito;
    private javax.swing.JButton botonAtras;
    private javax.swing.JLabel campoAutor;
    private javax.swing.JLabel campoFoto;
    private javax.swing.JLabel campoGenero;
    private javax.swing.JLabel campoIsbn;
    private javax.swing.JLabel campoPrecio;
    private javax.swing.JLabel campoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
